// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// import "dotenv/config";
// import { defineConfig } from "prisma/config";

// export default defineConfig({
//   schema: "prisma/schema.prisma",
//   migrations: {
//     path: "prisma/migrations",
//   },
//   datasource: {
//     url: process.env["DATABASE_URL"],
//   },
// });

const { PrismaClient } = require("./node_modules/@prisma/client");

export const prisma = new PrismaClient({
  adapter: "postgresql",
  url: process.env.benitoPepito_DATABASE_URL,
});
